### ISSUE TITLE
The NDI Monitor is black

### ISSUE THREAD

**Issue by lsandro** [satoshi0212/NDIHXSenderSample#2]
After I click the send button, the received information of NDI Analysis is normal, but NDI Monitor is black. Do you have any clue about this?

**Comment by satoshi0212** [comment]
Are you using Windows? In some cases, the iOS version of the library could not be received on Windows. The same implementation was able to receive on macOS.

It may be a different problem that you were able to receive with NDI Analysis, but just an FYI.

I will try it myself if a newer version is available in the SDK.

**Comment by lsandro** [comment]
Thank you very much for your reply, whether it is Windows or macOS, it is the same effect, NDI Monitor is black.

**Comment by lsandro** [comment]
After I installed libNDI_for_Mac.pkg, the NDI Monitor on the mac no longer has a black screen, and the video transmitted by your demo can be displayed correctly. However, Redist for Windows still does not solve the problem after installation, and it is currently being studied how to display Windows correctly.

**Comment by liumanfang** [comment]
我的NDI监视器也是黑屏，并且在安装了libNDI_for_Mac.pkg后，也是黑屏，可以请教一下解决方法吗？

**Comment by lsandro** [comment]
> 我的NDI监视器也是黑屏，并且在安装了libNDI_for_Mac.pkg后，也是黑屏，可以请教一下解决方法吗？

p_packet->data_size = (uint32_t)[avcData length]; // Correctly displayed on macOC
p_packet->data_size = packet_size; //  Correctly displayed on Windows
